version: "3.4"
services:
  redis:
    image: redis:5.0.3-alpine
    restart: always

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=job_orchestrator
      - POSTGRES_PASSWORD=muchsecurity
      - POSTGRES_DB=jobs
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  job-orchestrator:
    build: .
    restart: always
    command: celery -A tasks worker --loglevel=INFO
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
