"""Add transformation number to job request

Revision ID: 324348d8954b
Revises: e205f8466f50
Create Date: 2021-10-09 12:40:01.638378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324348d8954b'
down_revision = 'e205f8466f50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_request', sa.Column('transformation_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_request', 'transformation_number')
    # ### end Alembic commands ###
