"""Remove unique constraint for tx hash in job request

Revision ID: 4af8308e88ec
Revises: 324348d8954b
Create Date: 2021-11-17 11:54:00.604981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af8308e88ec'
down_revision = '324348d8954b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('job_request_transaction_hash_key', 'job_request', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('job_request_transaction_hash_key', 'job_request', ['transaction_hash'])
    # ### end Alembic commands ###
