"""Add unique constraint for tx hash in job request

Revision ID: 7d51b2d43a4a
Revises: 4af8308e88ec
Create Date: 2021-11-29 19:46:03.940915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d51b2d43a4a'
down_revision = '4af8308e88ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'job_request', ['transaction_hash'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_request', type_='unique')
    # ### end Alembic commands ###
