"""Add transformations to job requests

Revision ID: ae203134339e
Revises: bebed10aee6f
Create Date: 2021-09-02 13:55:20.954854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae203134339e'
down_revision = 'bebed10aee6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_request', sa.Column('transformation', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_request', 'transformation')
    # ### end Alembic commands ###
