"""Generate job request table

Revision ID: bebed10aee6f
Revises: 2458be8f1263
Create Date: 2021-08-30 22:53:45.473530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bebed10aee6f'
down_revision = '2458be8f1263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_request_hash', sa.String(length=155), nullable=False),
    sa.Column('payer', sa.String(length=155), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('task_id', sa.String(155), nullable=True),
    # sa.ForeignKeyConstraint(['task_id'], ['celery_taskmeta.task_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_request_id'), 'job_request', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_request_id'), table_name='job_request')
    op.drop_table('job_request')
    # ### end Alembic commands ###
