"""Remove unique constraint for block hash in job request

Revision ID: e205f8466f50
Revises: 4809f0d1b5fb
Create Date: 2021-10-04 16:39:41.482031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e205f8466f50'
down_revision = '4809f0d1b5fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('job_request_block_hash_key', 'job_request', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('job_request_block_hash_key', 'job_request', ['block_hash'])
    # ### end Alembic commands ###
