from transformers.ascii_art import ASCIIArt
from transformers.cartoonification import Cartoonifier
from transformers.sketch_art import SketchArt
from transformers.fast_neural_style import FastNeuralStyle
